sdm660-common: Fix Doze errors
device/asus/sdm660-common/DeviceDoze/src/com/advanced/settings/doze/DozeSettingsActivity.java:32: error: package com.android.settingslib.collapsingtoolbar.R does not exist
        getFragmentManager().beginTransaction().replace(com.android.settingslib.collapsingtoolbar.R.id.content_frame,                                                                                                                      ^

device/asus/sdm660-common/DeviceDoze/src/com/advanced/settings/doze/DozeSettingsFragment.java:60: error: incompatible types: DozeSetting
sFragment cannot be converted to OnMainSwitchChangeListener                                                                                     mSwitchBar.addOnSwitchChangeListener(this);
                                             ^                                                                                          Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output

Signed-off-by: muralivijay <muralidharan9845@gmail.com>